apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: london
  description: london demo
spec:
  type: openapi
  lifecycle: experimental
  owner: lab49-poc
  definition:
    $text: https://github.com/lab49-poc/london/blob/master/src/main/resources/api-docs.yaml
